version: '3.4'
services:
  app:
    build: .
    # Run bundle install and keep app service running
    command: bash -c "bundle install && tail -f /dev/null"
    volumes:
      - .:/myapp
    environment:
      DB_HOST: db_postgres
      DB_USER: postgres
    depends_on:
      - db_postgres
      - db_redis
    ports: 
      - 3000:3000
  db_postgres:
    image: groonga/pgroonga:2.1.8-alpine-11.1
    volumes:
      - production_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db_redis:
    image: redis:4.0-alpine
    volumes:
      - production_redis_data:/data
volumes:
  production_db_data:
  production_redis_data:
